const courses = [
  {
    title: "HTML Basics",
    description: "Introduction to HTML and web development.",
    duration: "45 mins",
    lesson: [
      "HTML Overview",
      "Tags & Elements",
      "Links & Images",
      "Forms",
      "Semantic HTML",
      "SEO Basics",
    ],
  },
  {
    title: "CSS Fundamentals",
    description: "Learn how to style web pages with CSS.",
    duration: "50 mins",
    lesson: [
      "Selectors",
      "Box Model",
      "Flexbox",
      "Grid Layout",
      "Responsive Design",
      "Animations",
    ],
  },
  {
    title: "JavaScript Essentials",
    description: "Core concepts of modern JavaScript.",
    duration: "60 mins",
    lesson: [
      "Variables & Types",
      "Functions",
      "DOM Manipulation",
      "ES6 Features",
      "Events",
      "Promises & Async/Await",
    ],
  },
  {
    title: "React Basics",
    description: "Introduction to React components and state management.",
    duration: "45 mins",
    lesson: [
      "React Overview",
      "JSX",
      "Components",
      "Props",
      "State",
      "Lifecycle Methods",
    ],
  },
  {
    title: "Advanced React",
    description: "Diving deeper into React with hooks and context.",
    duration: "60 mins",
    lesson: [
      "useState",
      "useEffect",
      "useContext",
      "Custom Hooks",
      "useReducer",
      "Performance Optimization",
    ],
  },
  {
    title: "React Router",
    description: "Learn routing and navigation in React apps.",
    duration: "40 mins",
    lesson: [
      "BrowserRouter",
      "Routes & Route",
      "useNavigate",
      "Dynamic Routing",
      "Protected Routes",
    ],
  },
  {
    title: "TypeScript for React",
    description: "Build React apps with TypeScript.",
    duration: "55 mins",
    lesson: [
      "Typing Props",
      "Typing State",
      "Interfaces & Types",
      "Generics",
      "Custom Types",
    ],
  },
  {
    title: "Node.js Basics",
    description: "Backend development with Node.js and Express.",
    duration: "70 mins",
    lesson: [
      "Node Core",
      "Express Setup",
      "Routing",
      "Middleware",
      "APIs",
      "Error Handling",
    ],
  },
  {
    title: "Database with MongoDB",
    description: "Using MongoDB in fullstack apps.",
    duration: "50 mins",
    lesson: [
      "Collections & Documents",
      "CRUD Operations",
      "Mongoose",
      "Schema & Models",
      "Aggregation",
    ],
  },
  {
    title: "Fullstack Integration",
    description: "Connecting frontend and backend.",
    duration: "80 mins",
    lesson: [
      "REST APIs",
      "Fetching Data",
      "JWT Authentication",
      "State Management",
      "Deployment",
    ],
  },
];

export { courses };